[/]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom1/', '/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom2/']

[custom-keybindings/custom1]
binding='<Alt>space'
command='rofi -show combi -combi-modes "window,drun,run" -modes combi'
name='rofi-switchWindow'

[custom-keybindings/custom2]
binding='<Primary><Alt>a'
command='flameshot gui'
name='screenCap'
