[/]
activate-window-menu=@as []
close=['<Primary><Alt>c']
move-to-workspace-1=['<Super><Shift>Home', '<Alt><Shift>1']
move-to-workspace-2=['<Alt><Shift>2']
move-to-workspace-3=['<Alt><Shift>3']
move-to-workspace-4=['<Alt><Shift>4']
move-to-workspace-5=['<Alt><Shift>5']
move-to-workspace-left=['<Super><Shift>Page_Up', '<Super><Shift><Alt>Left', '<Control><Shift><Alt>Left', '<Super><Control>Left']
move-to-workspace-right=['<Super><Shift>Page_Down', '<Super><Shift><Alt>Right', '<Control><Shift><Alt>Right', '<Super><Control>Right']
switch-applications=@as []
switch-applications-backward=@as []
switch-to-workspace-1=['<Alt>1']
switch-to-workspace-2=['<Alt>2']
switch-to-workspace-3=['<Alt>3']
switch-to-workspace-4=['<Alt>4']
switch-to-workspace-5=['<Alt>5']
switch-to-workspace-6=['<Alt>6']
switch-to-workspace-7=['<Alt>7']
toggle-maximized=['<Primary><Shift>f']
